### PR TITLE
JS SDK Nesting Example

### PR DESCRIPTION
**Pull request by idea404**
New area to docs: 

image

### CODE REVIEW

**Comment by idea404** [comment]
@bucanero I tried to fix the broken CI build check but can not seem to find the issue. The build works fine locally and on render

**Comment by gagdiez** [comment]
@idea404 should we add this as a "detail" (that you need to open to see) since it will be gone soon?

**Comment by idea404** [comment]
> @idea404 should we add this as a "detail" (that you need to open to see) since it will be gone soon?
> 
> ```
> <details>
> <summary>Title goes here</summary>
> </details>
> ```

Sounds good to me, will update

**Comment by idea404** [comment]
@gagdiez 
image

**Review by gagdiez — APPROVED** [review]

**Pull request merged**
