### PR TITLE
feat: docs localization

### PR DESCRIPTION
**Pull request by think-in-universe**
### Description

Introduce the following features:

- [X] docs translation management with Crowdin project: https://crowdin.com/project/near-docs
- [X] dropdown button for switching languages
- [X] add explicit heading IDs for markdown headings, which is important to make links consistent among languages
- [x] i18n support of tabs and sidebar, etc.

### To Do

- [x] test the i18n docs works correctly with Chinese
- [x] prototype with Chinese and Vietnamese
- [x] update CI for building i18n site

### Reference

1. Docusaurus i18n with Crowdin: https://docusaurus.io/docs/i18n/crowdin
2. Docusaurus CLI for write translations and heading IDs: https://docusaurus.io/docs/cli

### CODE REVIEW

**Comment by think-in-universe** [comment]
@thisisjoshford thanks Josh.

I need your help to fix the test, build and deployment in CI. 

1. `test-links` failed for the i18n routes such as /es, /fr, etc. need to figure out how to fix this;
2. before `build`, we need to download the latest translations from Crowdin. To run this successfully in CI, we need to add an [`CROWDIN_PERSONAL_TOKEN`](https://docusaurus.io/docs/i18n/crowdin#access-token) environment variable in Travis / Render.
3. for deployment, we should also sync the latest markdown docs to Crowdin once a new English version doc is created or modified. We can have a `postdeploy` script that run `docusaurus write-translations && crowdin upload` after a PR is merged. This also requires configure the [`CROWDIN_PERSONAL_TOKEN`](https://docusaurus.io/docs/i18n/crowdin#access-token) environment variable

**Comment by vitorebatista** [comment]
Hi @think-in-universe!
Would it be possible to add the Portuguese option in Crowdin? I have an initiative with the Portuguese Guild and we are working on this [Crowding project](https://crowdin.com/project/near-documentation/), we can move to near-docs from now on.

**Comment by think-in-universe** [comment]
@vitorebatista awesome. great progress!

I have enabled Portuguese: https://crowdin.com/project/near-docs/pt-PT

**Comment by vitorebatista** [comment]
@think-in-universe could you change to pt-BR instead of pt-PT?
Thanks!!

**Comment by think-in-universe** [comment]
> @think-in-universe could you change to pt-BR instead of pt-PT? Thanks!!

updated!

**Comment by think-in-universe** [comment]
> 3\. for deployment, we should also sync the latest markdown docs to Crowdin once a new English version doc is created or modified. We can have a `postdeploy` script that run `docusaurus write-translations && crowdin upload` after a PR is merged.

@bucanero can we add the command and sync the docs to Crowdin after PR is merged?

**Comment by think-in-universe** [comment]
the translated docs work well for Chinese and Vietnamese in the latest version:

- Getting Started in Chinese: https://docs-pr-874.onrender.com/zh-CN/docs/develop/basics/getting-started
- Epoch in Vietnamese: https://docs-pr-874.onrender.com/vi-VN/docs/concepts/epoch

**Comment by think-in-universe** [comment]
cool. I think we're ready to merge the feature now.

**Review by thisisjoshford — APPROVED** [review]
Awesome work guys! CROWDIN_PERSONAL_TOKEN has been added to you should be good to go.

**Review by bucanero — APPROVED** [review]

**Pull request merged**
