### PR TITLE
Update NOWNodes link.md

### PR DESCRIPTION
**Pull request by AnnaNodes**
Hello,

Could you please update NOWNodes link?

### CODE REVIEW

**Review by bucanero — APPROVED** [review]

**Comment by AnnaNodes** [comment]
Thank you so much!

How much time does it take usually to update it on the docs?

Now it looks same as before and I am afraid that I didn't submit correctly PR

**Comment by bucanero** [comment]
We are currently experiencing some deployment issues so recent changes are not showing up yet. It's not your fault so don't worry, as soon as we fix our publishing system the new URL will be available.

**Comment by bucanero** [comment]
Changes should be live now

**Comment by AnnaNodes** [comment]
Thank you so much, Damián! Looks perfect!

**Pull request merged**
