### PR TITLE
setup mixpanel

### PR DESCRIPTION
**Pull request by icerove**
set up mixpanel plugin

### CODE REVIEW

**Comment by icerove** [comment]
wait for property added

**Comment by icerove** [comment]
need to figure out the token we use though

**Comment by thisisjoshford** [comment]
> need to figure out the token we use though

Is this PR still a work in progress @icerove ?

**Comment by icerove** [comment]
yes. @thisisjoshford

**Comment by icerove** [comment]
will open a new one

**Review by thisisjoshford — APPROVED** [review]
Everything looks to be functioning normally on the Render link, let me know if you run into any issues on the Mixpanel side. :)

**Pull request merged**
