### PR TITLE
Breakdown RPC / API and REST Docs

### PR DESCRIPTION
**Pull request by bucanero**
This PR intends to break down the `RPC Endpoints` and `REST Server` API documents, from a single monolithic file to a bunch of smaller topic-specific articles.

Breakdown structure:

RPC Endpoints
-    Setup
-    Access Keys
-    Accounts / Contracts
-    Block / Chunk
-    Gas
-    Protocol
-    Network
-    Transactions
-    Sandbox

REST Server
-    Overview
-    Contracts
-    Utils
-    NFTs

### CODE REVIEW

**Review by frol — APPROVED** [review]
Looks good to me. My only concern is the old links which used to point to `/api/rpc` page, and usually with an anchor to a specific section. It seems those will be lost :disappointed:

**Comment by bucanero** [comment]
> Looks good to me. My only concern is the old links which used to point to `/api/rpc` page, and usually with an anchor to a specific section. It seems those will be lost 😞

Thanks for the feedback @frol ! I will add a redirect on Render so `/api/rpc` doesn't go to a dead link 404. I'll take a look if something can be done for the anchors.

**Comment by khorolets** [comment]
@thisisjoshford hey! Any ETA when this PR will be merged? I've finished the PR based on this one #811, don't want to mess things up.

**Comment by bucanero** [comment]
> @thisisjoshford hey! Any ETA when this PR will be merged? I've finished the PR based on this one #811, don't want to mess things up.

Hi @khorolets,
From my side, this PR is ready to be merged. I'll ping @thisisjoshford so he can review it.

**Review by thisisjoshford — APPROVED** [review]
Looks good! If we have our re-directs in Render ready to go then let's merge. :)

**Comment by thisisjoshford** [comment]
> @thisisjoshford hey! Any ETA when this PR will be merged? I've finished the PR based on this one #811, don't want to mess things up.

Approved and ready to merge. Just wanted to make sure we had our redirects ready in Render.

**Pull request merged**
