### PR TITLE
Add videos section under Develop » Tutorials

### PR DESCRIPTION
**Pull request by mikedotexe**
Adding basic content for videos to aid in discoverability.

### CODE REVIEW

**Comment by mikedotexe** [comment]
Broken link checker is wasting my time again. Here the first one is fine, then the next two (the two new markdown files I made fail)

```
Getting links from: http://localhost:5000/docs/quick-start/development-overview
|├───OK─── https://github.com/near/docs/tree/master/docs/quick-start/development-overview.md
├───OK─── https://docs.npmjs.com/creating-a-package-json-file
├───OK─── https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
├───OK─── https://github.com/nearprotocol/react-template
├───OK─── https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
├───OK─── https://jasmine.github.io/
├───OK─── https://jasmine.github.io/tutorials/your_first_suite
Finished! 116 links found. 109 excluded. 0 broken.
Getting links from: http://localhost:5000/docs/videos/accounts-keys
/├─BROKEN─ https://github.com/near/docs/tree/master/docs/videos/accounts-keys.md (HTTP_404)
├───OK─── https://www.youtube-nocookie.com/embed/ganXZ0Iw1C8
/├───OK─── https://nomicon.io/RuntimeSpec/Actions.html
├───OK─── https://www.youtube-nocookie.com/embed/4Q4K03t2P48
├───OK─── https://github.com/near/core-contracts/tree/master/multisig
|├───OK─── https://github.com/nearprotocol/near-contract-helper
Finished! 106 links found. 100 excluded. 1 broken.
Getting links from: http://localhost:5000/docs/videos/collections-u128-etc
/├─BROKEN─ https://github.com/near/docs/tree/master/docs/videos/collections-u128-etc.md (HTTP_404)
├───OK─── https://www.youtube-nocookie.com/embed/wC6CS7js-tc
├───OK─── https://stackoverflow.com/questions/64378144/why-cant-i-read-this-hashmap-in-a-near-contract/64438703#64438703
/├───OK─── https://docs.rs/near-sdk/2.0.0/near_sdk/collections/index.html
├───OK─── https://docs.rs/near-sdk/2.0.0/near_sdk/json_types/struct.U128.html
Finished! 97 links found. 92 excluded. 1 broken.
```

Of course these do not exist on the `master` branch, why is link checker looking for them there? Do we just merge in this case?

**Comment by thisisjoshford** [comment]
> Of course these do not exist on the `master` branch, why is link checker looking for them there? Do we just merge in this case?

Found the issue was a result of PR #511 (removed the GH edit button from whitelisted sites), fixed with PR #524 

Will push changes to this branch so CI will pass :)

**Comment by mikedotexe** [comment]
Passing, thanks for that @thisisjoshford!
By the way, I put in a request for the images to use as thumbnails/stills for the video. I haven't heard back and imagine this may take a little while. Hopefully not a blocker on getting this content merged.

**Comment by thisisjoshford** [comment]
> Passing, thanks for that @thisisjoshford!
> By the way, I put in a request for the images to use as thumbnails/stills for the video. I haven't heard back and imagine this may take a little while. Hopefully not a blocker on getting this content merged.

No prob! Not a blocker at all @mikedotexe, just a minor detail.  Merging now :)

**Pull request merged**
