### PR TITLE
With live editor

### PR DESCRIPTION
**Pull request by narwalsandeep**
Inline editor "React" as 4th Tab for various RPC. Provides Live response as user modifies the content. "nearexample.testnet" has been used for the config.

### CODE REVIEW

**Comment by bucanero** [comment]
hi @narwalsandeep , is this PR ready for review, or you're still working on it?

**Comment by bucanero** [comment]
hello @narwalsandeep , I had to revert your PR because the live editor has a conflict with the @saucelabs/theme-github-codeblock plugin.

We use the github-codeblock plugin to inject source code into an article directly from a github repository. For example: https://docs.near.org/docs/tutorials/contracts/nfts/enumeration

Please could you fix the conflict so we can merge your live editor? thanks!

**Comment by narwalsandeep** [comment]
hi @bucanero  yeah we tried to have a look at possible solution/fix but looks like this conflict is an open issue and cannot be solved at the moment. We have done an alternative solution and will raise PR in soon for this. Thanks.

**Comment by bucanero** [comment]
Perfect, thanks for the update! Feel free to open a new pull request if you find a workaround. 👍🏻

**Comment by narwalsandeep** [comment]
hi @bucanero please see this https://github.com/near/docs/pull/1044

**Pull request merged**
