### PR TITLE
Consolidating Docs into a single page

### PR DESCRIPTION
**Pull request by gagdiez**
Working on reducing the amount of navigational categories from 3 (concepts, build, tutorials) to 2 (docs, tutorials)

Notice that this is a re-organization of the top bar, sidebar and welcome page. The content of the docs has not changed except for minimal changes (such as changing a title)

### CODE REVIEW

**Review by bucanero — APPROVED** [review]

**Comment by gagdiez** [comment]
summoning @race-of-sloths

**Comment by race-of-sloths** [comment]
@gagdiez Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/gagdiez?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/gagdiez?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/gagdiez)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/gagdiez)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by race-of-sloths** [comment]
### 🔄 The PR has been merged.
>[!IMPORTANT]
This pull request is a part of the Race of Sloths and has not been scored yet. Scoring will close in 24 hours! 🕰️

**Comment by gagdiez** [comment]
@bucanero please score my contribution 🙏

**Comment by gagdiez** [comment]
```
you can give a score using @race-of-sloths score: <score> , where <score> is: 
    0/exclude - comma fix, trivial with no added value
    1 - small non-priority feature
    2 - medium non-priority feature, small bug-fix
    3 - small prioritized feature, bug-fix, major improvement
    5 - medium prioritized feature, small security vulnerability fix, a time-consuming trivial task
    8 - critical feature, medium vulnerability fix
    13 - significant vulnerability fix, game-changer contribution
    ```

**Comment by race-of-sloths** [comment]
### ❓Unknown command 
Please check the command and try again

**Comment by bucanero** [comment]
@race-of-sloths score 13

**Comment by bucanero** [comment]
> @bucanero please score my contribution 🙏

done 👍

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@bucanero, thank you for scoring this pull request in the Race of Sloths!

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 13!
You have received 150 (130 base + 10 weekly bonus + 10 monthly bonus) Sloth points for this contribution


Congratulations @gagdiez! Your PR was highly scored and you completed another monthly streak! To keep your monthly streak make another pull request next month and get 8+ score for it

**Pull request merged**
