### PR TITLE
docs: add empty support channel section to help page

### LINKED ISSUE #2328: [DOC] Add Support Channels Section to /help Page
### Documentation Type

Update Existing Documentation

### What needs documentation?

this is linked to closed & merged issue #2282, which focused on making a reusable “moving forward” component for docs pages. as a follow-up, this will add a new section to the `/help` page that lists and organizes all support channels for devs, like telegram, discord etc.

the goal is to make `/help` the go-to place for finding all support-related info in one spot.

### Acceptance Criteria

- [x] Add a new section titled "Support Channels" to the `/help` page.
- [x]  Create tables to list all support resources, including:
       - 21 Telegram chatrooms from the [Telegram folder](https://t.me/addlist/VWPcqJDOmXdkZTQ5).
       - 31 Telegram chatrooms listed on [NearBuilders](https://www.nearbuilders.com/), avoiding duplicates with the above.
- [x]  Include other channels like Discord, Zulip, and others.
- [x]  Use table columns: Name, Description, and Link (no "Latest Release" column).
- [x]  Keep the "Latest Release" column in existing GitHub-related sections unchanged.

### Resources & References

https://github.com/near/docs/issues/2282
https://docs.near.org/help
https://www.nearbuilders.com/
https://t.me/addlist/VWPcqJDOmXdkZTQ5

### Priority

🟡 P2 : Documentation Enhancement

### PR DESCRIPTION
**Pull request by goffxnca**
PR updates the `/help` page w/ 3 main parts:

- Main Support Channels: Added key channels like Telegram (Near Dev), Discord, Zulip, X, and Dev Hub.
- Telegram Folder (21 chats): Grouped 21 NEAR-related TG chats into 1 table w/ a folder link.
- NearBuilders Groups (15 chats): Picked 15 unique groups from the 31 on [nearbuilders.com](https://nearbuilders.com/). where 14 were already in the TG folder and 2 were dropped:
   https://t.me/near_sdk_js: links to a no longer exists personal acct.
   https://t.me/+lf7vb2MAEgdjOGQx: bio links to a sus/external group, now expired.
   
Live preview: [New Help Page](https://goffxnca.github.io/docs/help/).
Fixes #2328

### CODE REVIEW

**Comment by goffxnca** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
@goffxnca Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://race-of-sloths.com/images/bot-banner-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://race-of-sloths.com/images/bot-banner-light.svg">
    Shows inviting banner with latest news.
</picture>](https://race-of-sloths.com/latest-news)

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/goffxnca?type=bot&pr=near/docs/2329&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/goffxnca?type=bot&pr=near/docs/2329&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/goffxnca)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/goffxnca)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by bucanero — APPROVED** [review]

**Comment by race-of-sloths** [comment]
🥁  __Score it!__

@bucanero, please score the PR with `@race-of-sloths score [1/2/3/5/8/13]`. The contributor deserves it.
If no scoring is provided within 24 hours, this PR will be scored as 1 🦥

**Comment by bucanero** [comment]
@race-of-sloths score 3

**Pull request merged**
