### PR TITLE
Updated - Validators (Running The Node)

### PR DESCRIPTION
**Pull request by htafolla**
This includes all the latest information and detailed steps to setting up a validator.

### CODE REVIEW

**Comment by mikedotexe** [comment]
@dependabot rebase

**Comment by mikedotexe** [comment]
Thanks @htafolla for this, rebasing now and maybe @jimmy3dita can re-review this

**Comment by jimmy3dita** [comment]
This page needs two improvements before it can be merged:
1. some of the steps provide instructions on how to install and configure external tools (such as npm or Docker under Ubuntu). I think the guide should point the user to the installation pages maintained by the respective developers, instead of repeating them on this page.
2. some steps are outdated: now the staking pool is deployed using the "factory" from the initial contracts. Also, the `near stake` command is now almost completely deprecated, as the totality of validators now is using the staking pool.

**Comment by htafolla** [comment]
@jimmy3dita I updated the doc with the most current information and did some additional cleanup. Please let me know if further changes are needed.

**Comment by jimmy3dita** [comment]
If you solve the conflicts I'm happy to review and merge

**Comment by AnaisUrlichs** [comment]
@jimmy3dita @htafolla @thisisjoshford what is the status on this PR? Can we merge it? Are the information still up to date?

**Comment by thisisjoshford** [comment]
Cleaning up docs PR's... is this PR still relevant, or can it be closed @jimmy3dita?

**Pull request closed without merging**
